### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by esistegalaber** [absolutegalaber/yeoman-gradle-plugin#4]
Seems like the plugin is not working on windows :(

**Comment by giordanolins** [comment]
Josip, your suggested by email log info didn't apper. The outbut is listed below:

C:\Users\Home\Desktop\CFCMan_v0\web>gradle gruntBuild
:web:gruntBuild                                                                  
###### Version of grunt:       
:web:gruntBuild FAILED         
               
FAILURE: Build failed with an exception.
               
* What went wrong:
Execution failed for task ':web:gruntBuild'.
> A problem occurred starting process 'command 'grunt''
               
* Try:         
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
               
BUILD FAILED   
               
Total time: 7.173 secs

And the stacktrace output remains the same:

Caused by: java.io.IOException: Cannot run program "grunt" (in directory "C:\Users\Home\Desktop\CFCMan_v0\web\yo"): CreateProcess error=2, [...]

**Comment by giordanolins** [comment]
It worked like a charm. =)
Thanks for all your effort to make it work nice on windows :)

**Comment by esistegalaber** [comment]
Nice !
